apiVersion: apps/v1
kind: Deployment
metadata:
  # name: {{ printf "%s-%s" .Chart.Name "db" }}
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "cryostat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cryostat.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cryostat.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.core.securityContext | nindent 12 }}
          image: quay.io/cryostat/cryostat-db:latest # TODO
          imagePullPolicy: Always
          env:
          - name: POSTGRESQL_USER
            value: cryostat3
          - name: POSTGRESQL_PASSWORD
            value: cryostat3
          - name: POSTGRESQL_DATABASE
            value: cryostat3
          - name: PG_ENCRYPT_KEY
            value: REPLACEME
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            {{- toYaml .Values.core.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
