{{- if empty .Values.core.databaseSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db
  labels:
    {{- include "cryostat.labels" $ | nindent 4 }}
type: Opaque
immutable: true
data:
  CONNECTION_KEY: {{ include "cryostat.databaseConnectionKey" . }}
  ENCRYPTION_KEY: {{ include "cryostat.databaseEncryptionKey" . }}
{{- end -}}
