{{- $fullName := include "cryostat.fullname" . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cryostat.fullname" . }}
  labels:
    {{- include "cryostat.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "cryostat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cryostat.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cryostat.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.core.securityContext | nindent 12 }}
          image: "{{ .Values.core.image.repository }}:{{ .Values.core.image.tag }}"
          imagePullPolicy: {{ .Values.core.image.pullPolicy }}
          env:
          - name: QUARKUS_HTTP_HOST
            value: 0.0.0.0
          - name: QUARKUS_HTTP_PORT
            value: "8181"
          - name: QUARKUS_HTTP_PROXY_PROXY_ADDRESS_FORWARDING
            value: 'true'
          - name: QUARKUS_HTTP_PROXY_ALLOW_X_FORWARDED
            value: 'true'
          - name: QUARKUS_HTTP_PROXY_ENABLE_FORWARDED_HOST
            value: 'true'
          - name: QUARKUS_HTTP_PROXY_ENABLE_FORWARDED_PREFIX
            value: 'true'
          - name: QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION
            value: drop-and-create
          - name: QUARKUS_DATASOURCE_USERNAME
            value: cryostat3
          - name: QUARKUS_DATASOURCE_PASSWORD
            value: cryostat3
          - name: QUARKUS_DATASOURCE_JDBC_URL
            value: jdbc:postgresql://db:5432/cryostat3
            value: "jdbc:postgresql://localhost:5432/cryostat3"
          - name: STORAGE_BUCKETS_ARCHIVES_NAME
            value: archivedrecordings
          - name: QUARKUS_S3_ENDPOINT_OVERRIDE
            value: "http://localhost:9000"
          - name: QUARKUS_S3_PATH_STYLE_ACCESS
            value: "true"
          - name: QUARKUS_S3_AWS_REGION
            value: us-east-1
          - name: QUARKUS_S3_AWS_CREDENTIALS_TYPE
            value: static
          - name: QUARKUS_S3_AWS_CREDENTIALS_STATIC_PROVIDER_ACCESS_KEY_ID
            value: minioroot # TODO
          - name: QUARKUS_S3_AWS_CREDENTIALS_STATIC_PROVIDER_SECRET_ACCESS_KEY
            value: minioroot # TODO
          - name: AWS_ACCESS_KEY_ID
            value: minioroot # TODO
          - name: AWS_SECRET_ACCESS_KEY
            value: minioroot # TODO
          {{- if not .Values.minimal }}
          - name: GRAFANA_DATASOURCE_URL
            value: http://127.0.0.1:8080
          - name: GRAFANA_DASHBOARD_URL
            value: "{{ if .Values.grafana.ingress.enabled }}http{{ if (or (.Values.grafana.ingress.tls) (.Values.grafana.sslProxied)) }}s{{ end }}://{{ with index .Values.grafana.ingress.hosts 0 }}{{ .host }}{{ end }}{{ end }}"
          {{- end }}
          ports:
            - containerPort: 8181
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "/health/liveness"
              port: 8181
          startupProbe:
            httpGet:
              path: "/health/liveness"
              port: 8181
            failureThreshold: 18
          resources:
            {{- toYaml .Values.core.resources | nindent 12 }}
        - name: {{ printf "%s-%s" .Chart.Name "db" }}
          securityContext:
            {{- toYaml .Values.core.securityContext | nindent 12 }}
          image: quay.io/cryostat/cryostat-db:latest # TODO pin to a particular version
          imagePullPolicy: Always
          env:
          - name: POSTGRESQL_USER
            value: cryostat3
          - name: POSTGRESQL_PASSWORD
            value: cryostat3
          - name: POSTGRESQL_DATABASE
            value: cryostat3
          - name: PG_ENCRYPT_KEY
            value: REPLACEME
          ports:
            - containerPort: 5432
              protocol: TCP
        - name: {{ printf "%s-%s" .Chart.Name "s3" }}
          securityContext:
            {{- toYaml .Values.core.securityContext | nindent 12 }}
          image: docker.io/minio/minio:latest # TODO pin to a particular version
          imagePullPolicy: Always
          args:
          - server
          - /data
          - --address
          - localhost:9000
          # TODO add persistent volume
          env:
          - name: MINIO_ROOT_USER
            value: minioroot # TODO
          - name: MINIO_ROOT_PASSWORD
            value: minioroot # TODO
          - name: MINIO_DEFAULT_BUCKETS
            value: archivedrecordings
        {{- if not .Values.minimal }}
        - name: {{ printf "%s-%s" .Chart.Name "grafana" }}
          securityContext:
            {{- toYaml .Values.grafana.securityContext | nindent 12 }}
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          env:
          - name: JFR_DATASOURCE_URL
            value: http://127.0.0.1:8080
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          ports:
          - containerPort: 3000
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
          resources:
            {{- toYaml .Values.grafana.resources | nindent 12 }}
        - name: {{ printf "%s-%s" .Chart.Name "jfr-datasource" }}
          securityContext:
            {{- toYaml .Values.datasource.securityContext | nindent 12 }}
          image: "{{ .Values.datasource.image.repository }}:{{ .Values.datasource.image.tag }}"
          imagePullPolicy: {{ .Values.datasource.image.pullPolicy }}
          env:
          - name: LISTEN_HOST
            value: 127.0.0.1
          ports:
          - containerPort: 8080
            protocol: TCP
          livenessProbe:
            exec:
              command:
              - curl
              - --fail
              - http://127.0.0.1:8080
          resources:
            {{- toYaml .Values.datasource.resources | nindent 12 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if ((.Values.pvc).enabled) }}
      - name: {{ .Chart.Name }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}
      {{- end }}
      {{- if not ((.Values.pvc).enabled) }}
      - name: {{ .Chart.Name }}
        emptyDir: {}
      {{- end }}
