apiVersion: apps/v1
kind: Deployment
metadata:
  # name: {{ printf "%s-%s" .Chart.Name "db" }}
  name: s3
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "cryostat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cryostat.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cryostat.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.core.securityContext | nindent 12 }}
          image: docker.io/localstack/localstack:latest # TODO
          imagePullPolicy: Always
          env:
          - name: SERVICES
            value: s3
          - name: START_WEB
            value: "1"
          - name: DEFAULT_REGION
            value: us-east-1
          - name: PORT_WEB_UI
            value: "4577"
          ports:
            - containerPort: 4566
              protocol: TCP
          resources:
            {{- toYaml .Values.core.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
